[package]
name = "my-near-cli"
version = "0.1.0"
authors = ["FroVolod <frol_off@meta.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paw = "1.0"
structopt = { version = "0.3", features = ["paw"] }
